// ─────────────────────────────────────────────────────────
// Society Expenses Route
// Handles recording, listing, and deleting society expenses.
// Voucher numbers are auto-generated by the DB trigger (VCH-YYYY-NNNN).
// All writes are restricted to super_admin and committee.
// Reads are restricted to super_admin and committee as well —
// residents should not see society financial records.
// ─────────────────────────────────────────────────────────
const express = require('express');
const pool    = require('../db/pool');
const { requireLogin, requireRole } = require('../middleware/auth');

const router = express.Router();

const VALID_PAYMENT_MODES = [
  'cash','cheque','online_upi','online_neft',
  'online_rtgs','demand_draft'
];

// ─────────────────────────────────────────────────────────
// GET /api/expenses
// Returns all expenses, optionally filtered by month/year/category.
// Query params: ?month=05&year=2025&category=Electricity
// ─────────────────────────────────────────────────────────
router.get('/', requireLogin, requireRole('super_admin', 'committee'), async (req, res) => {
  try {
    const { month, year, category } = req.query;
    const conditions = [];
    const params     = [];

    if (year) {
      params.push(parseInt(year));
      conditions.push(`EXTRACT(YEAR FROM expense_date) = $${params.length}`);
    }
    if (month) {
      params.push(parseInt(month));
      conditions.push(`EXTRACT(MONTH FROM expense_date) = $${params.length}`);
    }
    if (category) {
      params.push(category);
      conditions.push(`category = $${params.length}`);
    }

    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';

    const result = await pool.query(
      `SELECT id, voucher_number, expense_date, category, description,
              vendor_name, vendor_gst_number, amount,
              amount_excluding_gst, gst_amount,
              payment_mode, invoice_number,
              created_at
       FROM society_expenses
       ${where}
       ORDER BY expense_date DESC, created_at DESC`,
      params
    );

    return res.json(result.rows);
  } catch (err) {
    console.error('GET /expenses error:', err);
    return res.status(500).json({ error: 'Could not load expenses.' });
  }
});

// ─────────────────────────────────────────────────────────
// GET /api/expenses/summary
// Returns aggregated KPI numbers:
//   - Total maintenance collected (all time)
//   - Expenses this calendar month
//   - Expenses this calendar year
//   - Net surplus (collected - yearly expenses)
// ─────────────────────────────────────────────────────────
router.get('/summary', requireLogin, requireRole('super_admin', 'committee'), async (req, res) => {
  try {
    const now         = new Date();
    const thisMonth   = now.getMonth() + 1;  // 1-12
    const thisYear    = now.getFullYear();

    // Total maintenance ever collected (from maintenance_payments)
    const collectedRes = await pool.query(
      `SELECT COALESCE(SUM(amount_paid), 0) AS total
       FROM maintenance_payments`
    );

    // Expenses this calendar month
    const monthExpRes = await pool.query(
      `SELECT COALESCE(SUM(amount), 0) AS total
       FROM society_expenses
       WHERE EXTRACT(YEAR  FROM expense_date) = $1
         AND EXTRACT(MONTH FROM expense_date) = $2`,
      [thisYear, thisMonth]
    );

    // Expenses this calendar year
    const yearExpRes = await pool.query(
      `SELECT COALESCE(SUM(amount), 0) AS total
       FROM society_expenses
       WHERE EXTRACT(YEAR FROM expense_date) = $1`,
      [thisYear]
    );

    // Maintenance collected this year (for surplus calc)
    const collectedYearRes = await pool.query(
      `SELECT COALESCE(SUM(amount_paid), 0) AS total
       FROM maintenance_payments
       WHERE EXTRACT(YEAR FROM payment_date) = $1`,
      [thisYear]
    );

    const totalCollected  = parseFloat(collectedRes.rows[0].total);
    const monthExpenses   = parseFloat(monthExpRes.rows[0].total);
    const yearExpenses    = parseFloat(yearExpRes.rows[0].total);
    const yearCollected   = parseFloat(collectedYearRes.rows[0].total);
    const netSurplus      = yearCollected - yearExpenses;

    return res.json({
      totalCollected,
      monthExpenses,
      yearExpenses,
      netSurplus,
      month: thisMonth,
      year:  thisYear,
    });
  } catch (err) {
    console.error('GET /expenses/summary error:', err);
    return res.status(500).json({ error: 'Could not load financial summary.' });
  }
});

// ─────────────────────────────────────────────────────────
// GET /api/expenses/categories
// Returns all distinct categories that have been used,
// merged with the default seeded list, so the frontend
// dropdown always has the full current list.
// ─────────────────────────────────────────────────────────
router.get('/categories', requireLogin, requireRole('super_admin', 'committee'), async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT DISTINCT category
       FROM society_expenses
       ORDER BY category`
    );
    return res.json(result.rows.map(r => r.category));
  } catch (err) {
    console.error('GET /expenses/categories error:', err);
    return res.status(500).json({ error: 'Could not load categories.' });
  }
});

// ─────────────────────────────────────────────────────────
// POST /api/expenses
// Records a new expense. The DB trigger auto-generates the
// voucher_number (VCH-YYYY-NNNN). Returns the new record
// including the generated voucher number.
// ─────────────────────────────────────────────────────────
router.post('/', requireLogin, requireRole('super_admin', 'committee'), async (req, res) => {
  try {
    const {
      expenseDate, category, description,
      vendorName, vendorGstNumber,
      amount, gstAmount, amountExcludingGst,
      paymentMode, invoiceNumber,
    } = req.body;

    // Required field validation
    if (!expenseDate || !category || !description || !vendorName || !amount || !paymentMode) {
      return res.status(400).json({
        error: 'Date, category, description, payee name, amount, and payment method are required.',
      });
    }
    if (!VALID_PAYMENT_MODES.includes(paymentMode)) {
      return res.status(400).json({ error: 'Invalid payment method.' });
    }

    const amt     = parseFloat(amount);
    const gstAmt  = parseFloat(gstAmount)         || 0;
    const baseAmt = parseFloat(amountExcludingGst) || (amt - gstAmt);

    if (isNaN(amt) || amt <= 0) {
      return res.status(400).json({ error: 'Amount must be a positive number.' });
    }

    // Derive financial year (Indian FY: Apr–Mar)
    const d   = new Date(expenseDate);
    const yr  = d.getMonth() >= 3 ? d.getFullYear() : d.getFullYear() - 1;
    const financialYear = `${yr}-${String(yr + 1).slice(2)}`;

    const result = await pool.query(
      `INSERT INTO society_expenses
        (expense_date, category, description,
         vendor_name, vendor_gst_number,
         amount, gst_amount, amount_excluding_gst,
         payment_mode, invoice_number,
         financial_year, paid_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::expense_payment_mode,$10,$11,$12)
       RETURNING id, voucher_number, expense_date, category, description,
                 vendor_name, amount, payment_mode`,
      [
        expenseDate, category, description,
        vendorName, vendorGstNumber || null,
        amt, gstAmt, baseAmt,
        paymentMode, invoiceNumber || null,
        financialYear, req.user.userId,
      ]
    );

    return res.status(201).json({
      message:       'Expense recorded successfully.',
      expense:       result.rows[0],
      voucherNumber: result.rows[0].voucher_number,
    });
  } catch (err) {
    console.error('POST /expenses error:', err);
    return res.status(500).json({ error: `Could not save expense: ${err.message}` });
  }
});

// ─────────────────────────────────────────────────────────
// POST /api/expenses/bulk
// Import multiple expense rows from an uploaded XLSX (parsed
// on the frontend and sent as a JSON array). Each row is
// processed independently — failures are reported but do not
// block the rest of the batch.
// ─────────────────────────────────────────────────────────
router.post('/bulk', requireLogin, requireRole('super_admin', 'committee'), async (req, res) => {
  try {
    const { expenses } = req.body;
    if (!Array.isArray(expenses) || expenses.length === 0) {
      return res.status(400).json({ error: 'No expense rows provided.' });
    }
    if (expenses.length > 500) {
      return res.status(400).json({ error: 'Maximum 500 rows per import.' });
    }

    const succeeded = [];
    const failed    = [];

    for (let i = 0; i < expenses.length; i++) {
      const r = expenses[i];
      try {
        const amt     = parseFloat(r.amount) || 0;
        const gstAmt  = parseFloat(r.gst_amount) || 0;
        const baseAmt = amt - gstAmt;
        const d       = new Date(r.date);
        const yr      = d.getMonth() >= 3 ? d.getFullYear() : d.getFullYear() - 1;
        const fy      = `${yr}-${String(yr + 1).slice(2)}`;
        const mode    = (r.payment_mode || 'cash').toLowerCase().replace(' ', '_');

        await pool.query(
          `INSERT INTO society_expenses
            (expense_date, category, description, vendor_name,
             vendor_gst_number, amount, gst_amount, amount_excluding_gst,
             payment_mode, invoice_number, financial_year, paid_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::expense_payment_mode,$10,$11,$12)`,
          [
            r.date, r.category || 'Others', r.description || '—',
            r.payee_name || '—', r.gst_number || null,
            amt, gstAmt, baseAmt,
            VALID_PAYMENT_MODES.includes(mode) ? mode : 'cash',
            r.bill_number || null, fy, req.user.userId,
          ]
        );
        succeeded.push(r);
      } catch (e) {
        failed.push({ row: r.description || `Row ${i + 1}`, error: e.message });
      }
    }

    return res.json({
      successCount: succeeded.length,
      failedCount:  failed.length,
      totalRows:    expenses.length,
      failed,
    });
  } catch (err) {
    console.error('POST /expenses/bulk error:', err);
    return res.status(500).json({ error: 'Bulk import failed.' });
  }
});

// ─────────────────────────────────────────────────────────
// DELETE /api/expenses/:id
// Super admin only — hard delete a recorded expense.
// ─────────────────────────────────────────────────────────
router.delete('/:id', requireLogin, requireRole('super_admin'), async (req, res) => {
  try {
    const result = await pool.query(
      `DELETE FROM society_expenses WHERE id = $1 RETURNING id, voucher_number`,
      [req.params.id]
    );
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Expense not found.' });
    }
    return res.json({ message: `Expense ${result.rows[0].voucher_number} deleted.` });
  } catch (err) {
    console.error('DELETE /expenses/:id error:', err);
    return res.status(500).json({ error: 'Could not delete expense.' });
  }
});

module.exports = router;
