// ─────────────────────────────────────────────────────────
// Society Expenses Route
// Handles recording, listing, and deleting society expenses.
// Voucher numbers are auto-generated by the DB trigger (VCH-YYYY-NNNN).
// All writes are restricted to super_admin and committee.
// Reads are restricted to super_admin and committee as well —
// residents should not see society financial records.
// ─────────────────────────────────────────────────────────
const express = require('express');
const pool    = require('../db/pool');
const { requireLogin, canDelete, canWrite, canManage } = require('../middleware/auth');

const router = express.Router();

const VALID_PAYMENT_MODES = [
  'cash','cheque','online_upi','online_neft',
  'online_rtgs','demand_draft'
];

// ─────────────────────────────────────────────────────────
// GET /api/expenses
// Returns all expenses, optionally filtered by month/year/category.
// Query params: ?month=05&year=2025&category=Electricity
// ─────────────────────────────────────────────────────────
router.get('/', requireLogin, canManage, async (req, res) => {
  try {
    const { month, year, category } = req.query;
    const conditions = [];
    const params     = [];

    if (year) {
      params.push(parseInt(year));
      conditions.push(`EXTRACT(YEAR FROM expense_date) = $${params.length}`);
    }
    if (month) {
      params.push(parseInt(month));
      conditions.push(`EXTRACT(MONTH FROM expense_date) = $${params.length}`);
    }
    if (category) {
      params.push(category);
      conditions.push(`category = $${params.length}`);
    }

    const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';

    const result = await pool.query(
      `SELECT id, voucher_number, expense_date, category, description,
              vendor_name, vendor_gst_number, amount,
              amount_excluding_gst, gst_amount,
              payment_mode, invoice_number,
              created_at
       FROM society_expenses
       ${where}
       ORDER BY expense_date DESC, created_at DESC`,
      params
    );

    return res.json(result.rows);
  } catch (err) {
    console.error('GET /expenses error:', err);
    return res.status(500).json({ error: 'Could not load expenses.' });
  }
});

// ─────────────────────────────────────────────────────────
// GET /api/expenses/summary
// Returns aggregated KPI numbers:
//   - Total maintenance collected (all time)
//   - Expenses this calendar month
//   - Expenses this calendar year
//   - Net surplus (collected - yearly expenses)
// ─────────────────────────────────────────────────────────
router.get('/summary', requireLogin, canManage, async (req, res) => {
  try {
    const now        = new Date();
    const thisMonth  = now.getMonth() + 1;   // 1–12
    const thisYear   = now.getFullYear();

    // Indian financial year runs Apr–Mar.
    // If current month is Jan/Feb/Mar we are still in the FY that started last April.
    const fyStart    = thisMonth >= 4 ? thisYear     : thisYear - 1; // April of FY start
    const fyEnd      = thisMonth >= 4 ? thisYear + 1 : thisYear;     // March of FY end
    const fyLabel    = `${fyStart}-${String(fyEnd).slice(-2)}`;      // e.g. "2025-26"

    // FY date range: 1 Apr fyStart → 31 Mar fyEnd
    const fyStartDate = `${fyStart}-04-01`;
    const fyEndDate   = `${fyEnd}-03-31`;

    // Total maintenance ever collected (all time)
    const collectedRes = await pool.query(
      `SELECT COALESCE(SUM(amount_paid), 0) AS total FROM maintenance_payments`
    );

    // Expenses this calendar month
    const monthExpRes = await pool.query(
      `SELECT COALESCE(SUM(amount), 0) AS total
       FROM society_expenses
       WHERE EXTRACT(YEAR  FROM expense_date) = $1
         AND EXTRACT(MONTH FROM expense_date) = $2`,
      [thisYear, thisMonth]
    );

    // Expenses this financial year (Apr–Mar)
    const yearExpRes = await pool.query(
      `SELECT COALESCE(SUM(amount), 0) AS total
       FROM society_expenses
       WHERE expense_date BETWEEN $1 AND $2`,
      [fyStartDate, fyEndDate]
    );

    // Maintenance collected this financial year (for surplus calc)
    const collectedYearRes = await pool.query(
      `SELECT COALESCE(SUM(amount_paid), 0) AS total
       FROM maintenance_payments
       WHERE payment_date BETWEEN $1 AND $2`,
      [fyStartDate, fyEndDate]
    );

    const totalCollected = parseFloat(collectedRes.rows[0].total);
    const monthExpenses  = parseFloat(monthExpRes.rows[0].total);
    const yearExpenses   = parseFloat(yearExpRes.rows[0].total);
    const yearCollected  = parseFloat(collectedYearRes.rows[0].total);
    const netSurplus     = yearCollected - yearExpenses;

    return res.json({
      totalCollected,
      monthExpenses,
      yearExpenses,
      netSurplus,
      month:   thisMonth,
      year:    thisYear,
      fyLabel,              // e.g. "2025-26"
      fyStart,              // e.g. 2025
      fyEnd,                // e.g. 2026
    });
  } catch (err) {
    console.error('GET /expenses/summary error:', err);
    return res.status(500).json({ error: 'Could not load financial summary.' });
  }
});

// ─────────────────────────────────────────────────────────
// GET /api/expenses/categories
// Returns all distinct categories that have been used,
// merged with the default seeded list, so the frontend
// dropdown always has the full current list.
// ─────────────────────────────────────────────────────────
router.get('/categories', requireLogin, canManage, async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT DISTINCT category
       FROM society_expenses
       ORDER BY category`
    );
    return res.json(result.rows.map(r => r.category));
  } catch (err) {
    console.error('GET /expenses/categories error:', err);
    return res.status(500).json({ error: 'Could not load categories.' });
  }
});

// ─────────────────────────────────────────────────────────
// POST /api/expenses
// Records a new expense. The DB trigger auto-generates the
// voucher_number (VCH-YYYY-NNNN). Returns the new record
// including the generated voucher number.
// ─────────────────────────────────────────────────────────
router.post('/', requireLogin, canWrite, async (req, res) => {
  try {
    const {
      expenseDate, category, description,
      vendorName, vendorGstNumber,
      amount, gstAmount, amountExcludingGst,
      paymentMode, invoiceNumber,
    } = req.body;

    // Required field validation
    if (!expenseDate || !category || !description || !vendorName || !amount || !paymentMode) {
      return res.status(400).json({
        error: 'Date, category, description, payee name, amount, and payment method are required.',
      });
    }
    if (!VALID_PAYMENT_MODES.includes(paymentMode)) {
      return res.status(400).json({ error: 'Invalid payment method.' });
    }

    const amt     = parseFloat(amount);
    const gstAmt  = parseFloat(gstAmount)         || 0;
    const baseAmt = parseFloat(amountExcludingGst) || (amt - gstAmt);

    if (isNaN(amt) || amt <= 0) {
      return res.status(400).json({ error: 'Amount must be a positive number.' });
    }

    // Derive financial year (Indian FY: Apr–Mar)
    const d   = new Date(expenseDate);
    const yr  = d.getMonth() >= 3 ? d.getFullYear() : d.getFullYear() - 1;
    const financialYear = `${yr}-${String(yr + 1).slice(2)}`;

    const result = await pool.query(
      `INSERT INTO society_expenses
        (expense_date, category, description,
         vendor_name, vendor_gst_number,
         amount, gst_amount, amount_excluding_gst,
         payment_mode, invoice_number,
         financial_year, paid_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::expense_payment_mode,$10,$11,$12)
       RETURNING id, voucher_number, expense_date, category, description,
                 vendor_name, amount, payment_mode`,
      [
        expenseDate, category, description,
        vendorName, vendorGstNumber || null,
        amt, gstAmt, baseAmt,
        paymentMode, invoiceNumber || null,
        financialYear, req.user.userId,
      ]
    );

    return res.status(201).json({
      message:       'Expense recorded successfully.',
      expense:       result.rows[0],
      voucherNumber: result.rows[0].voucher_number,
    });
  } catch (err) {
    console.error('POST /expenses error:', err);
    return res.status(500).json({ error: `Could not save expense: ${err.message}` });
  }
});

// ─────────────────────────────────────────────────────────
// POST /api/expenses/bulk
// Import multiple expense rows from an uploaded XLSX (parsed
// on the frontend and sent as a JSON array). Each row is
// processed independently — failures are reported but do not
// block the rest of the batch.
// ─────────────────────────────────────────────────────────
router.post('/bulk', requireLogin, canWrite, async (req, res) => {
  try {
    const { expenses } = req.body;
    if (!Array.isArray(expenses) || expenses.length === 0) {
      return res.status(400).json({ error: 'No expense rows provided.' });
    }
    if (expenses.length > 500) {
      return res.status(400).json({ error: 'Maximum 500 rows per import.' });
    }

    const succeeded = [];
    const failed    = [];

    for (let i = 0; i < expenses.length; i++) {
      const r = expenses[i];
      try {
        const amt     = parseFloat(r.amount) || 0;
        const gstAmt  = parseFloat(r.gst_amount) || 0;
        const baseAmt = amt - gstAmt;
        const d       = new Date(r.date);
        const yr      = d.getMonth() >= 3 ? d.getFullYear() : d.getFullYear() - 1;
        const fy      = `${yr}-${String(yr + 1).slice(2)}`;
        const modeRaw = String(r.payment_mode || 'cash').trim().toLowerCase().replace(/\s+/g,'_');
        const modeMap = { cheque:'cheque', check:'cheque', upi:'online_upi', neft:'online_neft',
                          rtgs:'online_rtgs', dd:'demand_draft', imps:'online_neft' };
        const mode = VALID_PAYMENT_MODES.includes(modeRaw) ? modeRaw : (modeMap[modeRaw] || 'cash');

        await pool.query(
          `INSERT INTO society_expenses
            (expense_date, category, description, vendor_name,
             vendor_gst_number, amount, gst_amount, amount_excluding_gst,
             payment_mode, invoice_number, financial_year, paid_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::expense_payment_mode,$10,$11,$12)`,
          [
            r.date, r.category || 'Others', r.description || '—',
            r.payee_name || '—', r.gst_number || null,
            amt, gstAmt, baseAmt,
            VALID_PAYMENT_MODES.includes(mode) ? mode : 'cash',
            r.bill_number || null, fy, req.user.userId,
          ]
        );
        succeeded.push(r);
      } catch (e) {
        failed.push({ row: r.description || `Row ${i + 1}`, error: e.message });
      }
    }

    return res.json({
      successCount: succeeded.length,
      failedCount:  failed.length,
      totalRows:    expenses.length,
      failed,
    });
  } catch (err) {
    console.error('POST /expenses/bulk error:', err);
    return res.status(500).json({ error: 'Bulk import failed.' });
  }
});

// ─────────────────────────────────────────────────────────
// PATCH /api/expenses/:id — edit an existing expense record
// Restricted to canDelete roles (admin, president, secretary, treasurer)
// ─────────────────────────────────────────────────────────
router.patch('/:id', requireLogin, canDelete, async (req, res) => {
  try {
    const { id } = req.params;
    const {
      expenseDate, category, description,
      vendorName, vendorGstNumber,
      amount, gstAmount, paymentMode, invoiceNumber,
    } = req.body;

    const current = await pool.query(
      `SELECT * FROM society_expenses WHERE id = $1`, [id]
    );
    if (current.rows.length === 0) {
      return res.status(404).json({ error: 'Expense not found.' });
    }

    const e = current.rows[0];
    const newAmt     = amount      !== undefined ? parseFloat(amount)    : parseFloat(e.amount);
    const newGst     = gstAmount   !== undefined ? parseFloat(gstAmount) : parseFloat(e.gst_amount || 0);
    const newBase    = newAmt - newGst;
    const newMode    = paymentMode || e.payment_mode;

    if (!VALID_PAYMENT_MODES.includes(newMode)) {
      return res.status(400).json({ error: 'Invalid payment method.' });
    }

    await pool.query(
      `UPDATE society_expenses SET
         expense_date       = COALESCE($1, expense_date),
         category           = COALESCE($2, category),
         description        = COALESCE($3, description),
         vendor_name        = COALESCE($4, vendor_name),
         vendor_gst_number  = $5,
         amount             = $6,
         gst_amount         = $7,
         amount_excluding_gst = $8,
         payment_mode       = $9::expense_payment_mode,
         invoice_number     = $10,
         updated_at         = NOW()
       WHERE id = $11`,
      [
        expenseDate   || null,
        category      || null,
        description   || null,
        vendorName    || null,
        vendorGstNumber !== undefined ? (vendorGstNumber || null) : e.vendor_gst_number,
        newAmt, newGst, newBase,
        newMode,
        invoiceNumber !== undefined ? (invoiceNumber || null) : e.invoice_number,
        id,
      ]
    );

    return res.json({ message: 'Expense updated.' });
  } catch (err) {
    console.error('PATCH /expenses/:id error:', err);
    return res.status(500).json({ error: `Could not update expense: ${err.message}` });
  }
});

// ─────────────────────────────────────────────────────────
// DELETE /api/expenses/:id
// Super admin only — hard delete a recorded expense.
// ─────────────────────────────────────────────────────────
router.delete('/:id', requireLogin, canDelete, async (req, res) => {
  try {
    const result = await pool.query(
      `DELETE FROM society_expenses WHERE id = $1 RETURNING id, voucher_number`,
      [req.params.id]
    );
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Expense not found.' });
    }
    return res.json({ message: `Expense ${result.rows[0].voucher_number} deleted.` });
  } catch (err) {
    console.error('DELETE /expenses/:id error:', err);
    return res.status(500).json({ error: 'Could not delete expense.' });
  }
});

module.exports = router;
